### ISSUE TITLE
getInbox() getChatMessages($author)

### ISSUE THREAD

**Issue by ghost** [mikechip/whatsapp-api-messenger-sdk#1]
Hi Mike,

Was wondering how does getInbox() and getChatMessages($author) work as I'm getting null after doing these below (both separate files):

// get-chat-messages.php
$token = [token];
$author = [chatId]; // tested with both [number]@c.us and [number]-[number]@g.us
$api = new ApiMessenger($token);
$result = $api->getChatMessages($author);
var_dump($results);

// get-inbox.php
$token = [token];
$api = new ApiMessenger($token);
$result = $api->getInbox();
var_dump($results);

I was expecting getInbox() to have the same behaviour as this below:

$url = 'https://app.api-messenger.com/messages?token='.$token;
$data = file_get_contents($url);
$results = json_decode($data, true);
var_dump($results);

**Comment by bssth** [comment]
Hi!

Could you send output of this?

```
var_dump(
  $api->query('messages', ['new' => 1])
);
```

**Comment by ghost** [comment]
`var_dump(
  $api->query('messages', ['new' => 1])
);`

Results in:
string(43) "{"status":"OK","pager":{"totalsMessage":0}}"

**Comment by bssth** [comment]
It seems like your inbox is empty or something else went wrong. 

Let's check status:
`var_dump( $api->query('go', []) );`

I believe it's api-messenger's problem

**Comment by Daniel-Richard** [comment]
That will result in:

string(0) ""

**Comment by mikechip** [comment]
It's extremely hard to say what happened. Have you visited https://api-messenger.com/my/? Is your account active?

**Comment by ghost** [comment]
That will result in:

string(0) ""

--

I'm also getting this:

file_get_contents(https://app.api-messenger.com/go?token=[token]): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

**Comment by bssth** [comment]
Try to visit https://app.api-messenger.com/go?token=[token] via browser. Do you get any errors?

**Comment by ghost** [comment]
Yeps. The sendMessage and sendFile are alright though. I'm using a modified version of the original script. It's the getInbox and getChatMessages that I wasn't able to get these 2 to work.

**Comment by bssth** [comment]
getInbox() was my own helper function a long time ago, so it may be broken. 

I will try it myself tonight and tell you if it will be fixed.

**Comment by bssth** [comment]
@Daniel-Richard, I updated repository. Now it use curl and own exception. It make easier to diagnose a problem.

Let me know if you try again.
